// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

const evenFib = n => {
  let secondToLastValue = 0;
  let lastValue = 1;
  let sumOfEvenValues = 0;

  while (lastValue <= n) {
    let nextValue = secondToLastValue + lastValue;
    if (nextValue % 2 === 0) {
      sumOfEvenValues += nextValue;
    }
    secondToLastValue = lastValue;
    lastValue = nextValue;
  }

  return sumOfEvenValues;
};

// tests
console.log(evenFib(4000000)); // 4613732
